frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['?'],
                        'actions' => [
                            'login', 
                            'request-password-reset', 
                            'reset-password',
                        ],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'actions' => [
                            'users',
                        ],
                        'matchCallback' => function ($rule, $action) {
                            return Yii::$app->user->identity->isAdmin;
                        },
                    ],
                ],
                'denyCallback' => function ($rule, $action) {
                    return $this->redirect(['site/login']);
                }
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        \Yii::$app->view->registerMetaTag([
            'name' => 'baseUrl',
            'content' => \yii\helpers\Url::base(Yii::$app->params['urlType']).'/',
        ]);

        if (!parent::beforeAction($action)) {
            return false;
        }

        return true;
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        $this->layout = 'login';
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    // public function actionUsers()
    // {
    //     return $this->render('users');
    // }

    public function actionConfig()
    {
        return $this->render('config');
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionAccount()
    {
        return $this->render('account');
    }

    public function actionTemplate($content)
    {
        return $this->renderPartial('templates/'.$content);
    }
}

frontend/views/layouts/_header.php
<?php
use yii\helpers\Html;

?>

<header class="main-header">
    <!-- Logo -->
    <a href="<?=Yii::$app->homeUrl?>" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>CIF</b></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><small style="opacity:.5;font-size:14px;">crawlbot</small><b>CIF</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button"><i class="fa fa-bars"></i></a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">
                      <span class="hidden-xs">哈囉，<?=@Yii::$app->user->identity->first_name?>！</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="<?=Yii::getAlias('@web/img/deadpool.png')?>" class="img-circle" alt="User Image">
                        </li>
                        <!-- Menu Body -->
                        <li class="user-body">
                            <div class="row">
                                <div class="col-xs-4 text-center pull-right">
                                  <?=Html::a('登出', ['site/logout'], ['data-method'=>'post'])?>
                                </div>
                            </div>
                            <!-- /.row -->
                        </li>
                    </ul>
                </li>

                <li>
                    <?=Html::a('登出 <i class="fas fa-sign-out-alt"></i>', ['site/logout'], ['data-method'=>'post'])?>
                </li>
            </ul>
        </div>
    </nav>
</header>

frontend/views/layouts/_sidenav.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
$act = Yii::$app->controller->action->id;
$ctl = Yii::$app->controller->id;
$page = "{$ctl}/{$act}";
?>


<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li style="padding:0 10px;">
                <button class="btn btn-block btn-flat" ng-class="{true:'btn-default',false:'btn-warning'}[running]" style="margin:20px auto;" ng-click="toggleBot()">
                    <span ng-if="!running">啟動機器人爬蟲</span>
                    <span ng-if="running">停用機器人爬蟲</span>
                </button>
            </li>
            <li class="header">主要功能</li>
            <li class="<?=($page=='site/index')?' active':''?>">
                <a href="<?=Yii::$app->homeUrl?>"><i class="fa fa-tachometer-alt"></i> <span>資訊總覽</span></a>
            </li>
                <li class="<?=($page=='site/account')?' active':''?>">
                    <a href="<?=Url::to(['site/account'])?>"><i class="fas fa-user-circle"></i> <span>帳戶設定</span></a>
                </li>
            <?php if(Yii::$app->user->identity->isAdmin):?>
                <li class="header">管理員功能</li>
                <li class="<?=($page=='site/config')?' active':''?>">
                    <a href="<?=Url::to(['site/config'])?>"><i class="fa fa-cog"></i> <span>系統設定</span></a>
                </li>
            <?php endif;?>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

frontend/views/layouts/error.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\AppAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use common\widgets\Alert;

AppAsset::register($this);
$page = Yii::$app->controller->id.'/'.Yii::$app->controller->action->id;

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">

<head>
<meta charset="<?= Yii::$app->charset ?>">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<?= Html::csrfMetaTags() ?>
<title>
<?= Html::encode($this->title) ?>
</title>
<?php $this->head() ?>
</head>

<body class="hold-transition login-page" ng-app="adminApp" ng-controller="DefaultController">
<?php $this->beginBody() ?>
<?= Alert::widget() ?>
<?= $content ?>


<?php $this->endBody() ?>
</body>

</html>
<?php $this->endPage() ?>

frontend/views/layouts/login.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" ng-app="frontendApp">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="hold-transition register-page">
<?php $this->beginBody() ?>
<?= $content ?>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

frontend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use frontend\assets\AppAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use common\widgets\Alert;

AppAsset::register($this);
$page = Yii::$app->controller->id.'/'.Yii::$app->controller->action->id;

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="hold-transition skin-blue sidebar-mini" ng-app="adminApp">
<?php $this->beginBody() ?>

<!-- Site wrapper -->
<div class="wrapper" ng-controller="DefaultController">
    <?=$this->render('_header'); ?>

    <?=$this->render('_sidenav'); ?>
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
      <?= Alert::widget() ?>
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        <?=$this->title?>
      </h1>

        <?= Breadcrumbs::widget([
            'homeLink' => [
                'label' => '<i class="fa fa-tachometer-alt"></i> 資訊總覽', 
                'url' => Yii::$app->homeUrl,
            ],
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            'encodeLabels' => false,
        ]) ?>
    </section>

    <!-- Main content -->
    <section class="content">
        <?= $content ?>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-left hidden-xs">
    </div>
    <div class="pull-right hidden-xs">
      <?= Yii::powered() ?> <b>Version</b> 2.4.0 
    </div>
      &copy; <?= Html::encode(Yii::$app->name) ?> <?= date('Y') ?>
    reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
      <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-cog"></i></a></li>

      <!-- <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li> -->
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- Home tab content -->
      <div class="tab-pane" id="control-sidebar-home-tab">
      </div>

      <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
      <!-- /.tab-pane -->
    </div>
  </aside>
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>